### PR TITLE
[ETFE-2858] - Added movement tab

### PR DESCRIPTION
**Pull request by LewisMitchell**

### CODE REVIEW

**Comment by LewisMitchell** [comment]
Need to look at how to retrieve some of the fields from the movement view response

**Comment by LewisMitchell** [comment]
There is a lot going on in this PR:

- Got some reverse engineering from the movement view response from CoD. In CaM we know specifically what the movement type is but this gets abstracted when sent to Core so we have to figure out (using MovementScenario) what the movement type is
- Reads in IE818 to figure out if the movement has been receipted, what the status was and when the movement items arrived
- Should go in with https://github.com/hmrc/emcs-tfe/pull/110
- Test data is not available for all the scenarios so I've had to rely on unit tests
- eAD status explanation was not included in the copydeck so I asked UCD who provided a spreadsheet (link in ticket)
- Refactored the coverage so that it ignores all the fluency models

**Review by james-work-account — APPROVED** [review]
Approved with caveats:

- Please update stub data so there's a movement in there which shows the RoR row, maybe one movement per RoR status
- ~Please update stub data so there's a movement in there which shows the "predicted" row~ Just make sure not every movement has a RoR, so at least one movement has a "predicted" row 😁

**Comment by LewisMitchell** [comment]
James has kindly picked up the changes and a separate PR is going to be raised to address the caveats

**Pull request merged**
